# Site settings
title: Ali Zaidi
email: alyzaidi@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Neuroscientist / Data Scientist with a passion for healthcare and medical technology.
baseurl:  # the subpath of your site, e.g. /blog/
url:  https://adzaidi.com
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: blue

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

plugins:
 - github-pages
 - jekyll-paginate

author:
  name   : "Ali Zaidi"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Neuroscientist / Data scientist with a passion for healthcare analytics."
  location: Vancouver, BC, Canada
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/adzaidi"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theonlyid"

    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.ca/citations?user=6kD2oIwAAAAJ"

    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/namesakeali"

    - label: "Resume"
      icon: "fas fa-file-pdf"
      url: "http://theonlyid.github.io/assets/docs/resume.pdf"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/adzaidi"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/theonlyid"

    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.ca/citations?user=6kD2oIwAAAAJ"

    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/namesakeali"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  tutorials:
    output: true
    permalink: /tutorials/:path/
  posts:
    output: true
    permalink: /posts/:path/



category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/